server:
  servlet:
    context-path: /
  port: 8081


spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@117.72.68.245:1521:helowin
    username: cdc
    password: aaBB11@@
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      keep-alive: true
      keep-alive-between-time-millis: 66000
      test-on-borrow: true
      test-on-return: false
      test-while-idle: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
